### ISSUE TITLE
Use express to create Socket.io Application

### ISSUE THREAD

**Issue by skyzh** [dokidaku/fuwafuta#1]
Try this:

```
npm install express-generator -g
express server && cd server
npm install
```

**Comment by skyzh** [comment]
View http://expressjs.com/en/starter/generator.html for usage.

**Comment by Pisces000221** [comment]
https://github.com/dokidaku/TwoDoubleThree-Connect/blob/master/README_zh.md#%E5%AE%89%E8%A3%85%E4%B8%8E%E9%85%8D%E7%BD%AE →Simpler

**Comment by skyzh** [comment]
www
